<a href="https://colab.research.google.com/github/babyaced/Python-Machine-Learning/blob/master/YelpDataAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Choose one of steps with letter options

#First Install DeltaTFIDF Vectorizer

In [ ]:
#Install Delta TFIDF Vectorizer
!pip install sklearn-deltatfidf
!pip install libsvm

     |████████████████████████████████| 174kB 6.0MB/s 
  Created wheel for libsvm: filename=libsvm-3.23.0.4-cp36-cp36m-linux_x86_64.whl size=233336 sha256=c760d12618910b059835af93990aae20789f0460e24fb312fd3cfe8a63e26890
  Stored in directory: /root/.cache/pip/wheels/5e/9e/b5/dbb033107407eec2f52b8cd24cf024a4b9ec8b62ea5aee995a
Successfully built libsvm


# 1) Import libraries and download Datasets

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import string # Imports the library



import nltk  #imports the natural language toolkit
from nltk.corpus import stopwords

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

#Import Delta TFIDF Vectorizer
from sklearn_deltatfidf import DeltaTfidfVectorizer 

from imblearn.over_sampling import RandomOverSampler
from imblearn.over_sampling import SMOTE

from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import train_test_split

from sklearn.pipeline import Pipeline
from imblearn.pipeline import make_pipeline

from sklearn.naive_bayes import MultinomialNB
from sklearn import svm
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import precision_score, recall_score, f1_score

nltk.download('wordnet')
nltk.download('stopwords') # download stopwords dataset

stopwords = stopwords.words('english')

print(stopwords)



/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'a

# 2a) Use Smaller Dataset

In [ ]:
# 980 review dataset
data = pd.read_csv('YelpDataset1000.csv')

#print('X Length: ',len(X), ' X Shape: ', X.shape)

data.dropna()
data['review']=data.review.str[2:-2]
data['author']=data.author.str[2:-2]
data['date']=data.date.str[2:-2]
data['rating']=data.rating.str[2:-2]
data['restaurant']=data.restaurant.str[2:-2]
data['rating']=data.rating.str[:1]
data['rating']= pd.to_numeric(data['rating'])

print('1 Star Ratings ',len(data[data['rating']==1]))
print('2 Star Ratings ',len(data[data['rating']==2]))
print('3 Star Ratings ',len(data[data['rating']==3]))
print('4 Star Ratings ',len(data[data['rating']==4]))
print('5 Star Ratings ',len(data[data['rating']==5]))

FileNotFoundError: ignored

# 2b) Use Bigger Dataset

In [5]:
# 10,000 review dataset
data = pd.read_csv('YelpDataset10000(1).csv')

data.dropna()

print('1 Star Ratings ',len(data[data['stars']==1]))
print('2 Star Ratings ',len(data[data['stars']==2]))
print('3 Star Ratings ',len(data[data['stars']==3]))
print('4 Star Ratings ',len(data[data['stars']==4]))
print('5 Star Ratings ',len(data[data['stars']==5]))

data.head()


1 Star Ratings  749
2 Star Ratings  927
3 Star Ratings  1461
4 Star Ratings  3526
5 Star Ratings  3337


stars                                               text
0      1  U can go there n check the car out. If u wanna...
1      1  Disgusting!  Had a Groupon so my daughter and ...
2      1  I've eaten here many times, but none as bad as...
3      1  I have always been a fan of Burlington's deals...
4      1  Another night meeting friends here.  I have to...

# 2c) Use Balanced Dataset

In [ ]:
# 3745 review dataset
data = pd.read_csv('YelpDataset3745.csv')

data.dropna()

print('1 Star Ratings ',len(data[data['stars']==1]))
print('2 Star Ratings ',len(data[data['stars']==2]))
print('3 Star Ratings ',len(data[data['stars']==3]))
print('4 Star Ratings ',len(data[data['stars']==4]))
print('5 Star Ratings ',len(data[data['stars']==5]))



1 Star Ratings  749
2 Star Ratings  749
3 Star Ratings  749
4 Star Ratings  749
5 Star Ratings  749


# (Optional): Restrict Dataset to 1 and 5 star reviews

In [ ]:
data = data[(data['rating'] == 1) | (data['rating'] == 5)]

# 3a) Clean and Lemmatize Reviews

In [7]:
#Could be detrimental to accuracy
wn=nltk.WordNetLemmatizer()

def clean_review(revw):
   #remove weird char
  revw = revw.replace('xa0',' ')

  #remove punctuation
  nopunc = [char for char in revw if char not in string.punctuation]
  nopunc = ''.join(nopunc)

  #remove stopwords
  token_text = [word for word in nopunc.split() if word.lower() not in stopwords]

  #perform lemmatization
  cleantext = ' '.join(wn.lemmatize(word) for word in token_text)
    
  return cleantext

data['cleantext'] = data['text'].apply(clean_review)


# 3b) Only Clean Reviews

In [ ]:
def clean_review(revw):
  #remove weird char
  revw = revw.replace('xa0',' ')

  #remove punctuation
  nopunc = [char for char in revw if char not in string.punctuation]
  nopunc = ''.join(nopunc)

  #remove stopwords
  token_text = [word for word in nopunc.split() if word.lower() not in stopwords]

  #skip lemmatization
  cleantext = ' '.join(word for word in token_text)
    
  return cleantext

data['cleantext'] = data['text'].apply(clean_review)

  



# Cross Validation

In [ ]:
def cv(k, X,Y, pipeline, average_method):
  kfold = StratifiedKFold(n_splits=k, shuffle=True, random_state=777)
  accuracy = []
  precision = []
  recall = []
  f1 = []
  for train, test in kfold.split(X, Y):

      fit = pipeline.fit(X[train], Y[train])
      prediction = fit.predict(X[test])
      scores = fit.score(X[test],Y[test])
        
      accuracy.append(scores * 100)
      precision.append(precision_score(Y[test], prediction, average=average_method)*100)
      print('              1            2             3            4            5')
      print('precision:',precision_score(Y[test], prediction, average=None))
      recall.append(recall_score(Y[test], prediction, average=average_method)*100)
      print('recall:   ',recall_score(Y[test], prediction, average=None))
      f1.append(f1_score(Y[test], prediction, average=average_method)*100)
      print('f1 score: ',f1_score(Y[test], prediction, average=None))
      print('-'*50)

  print("accuracy: %.2f%% (+/- %.2f%%)" % (np.mean(accuracy), np.std(accuracy)))
  print("precision: %.2f%% (+/- %.2f%%)" % (np.mean(precision), np.std(precision)))
  print("recall: %.2f%% (+/- %.2f%%)" % (np.mean(recall), np.std(recall)))
  print("f1 score: %.2f%% (+/- %.2f%%)" % (np.mean(f1), np.std(f1)))

#4a) Use Count Vectorizer

In [ ]:
#Count Vectorizer
ngram_vect = CountVectorizer(ngram_range=(1,1))
cv = ngram_vect.fit_transform(data['cleanReview'])

X = cv
y = data['rating']

#print(X)
#print(y)

print('X Shape: ', X.shape)
print(' y Shape: ', y.shape)

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.33, random_state=42)

X Shape:  (10000, 34038)
 y Shape:  (10000,)


#4b) Use Delta TFIDF Vectorizer

---



In [19]:
dtfidf = DeltaTfidfVectorizer(ngram_range=(1,3))
rating = data['stars'].tolist()
review = data['cleantext'].tolist()
review = [str(i) for i in review]
dtv = dtfidf.fit_transform(review, rating)

X = dtv
y = data['stars']

print('X Shape: ', X.shape)
print('y Shape: ', y.shape)

X_train, X_test, y_train, y_test = train_test_split(dtv, rating, test_size=0.33, random_state=42)

TypeError: ignored

# 4c) Use TFIDF Vectorizer

In [21]:
tfidf = TfidfVectorizer(ngram_range=(1,3))
rating = data['stars'].tolist()
review = data['cleantext'].tolist()
review = [str(i) for i in review]
tv = tfidf.fit_transform(review)

X = tv
y = data['stars']

print('X Shape: ', X.shape)
print('y Shape: ', y.shape)

X_train, X_test, y_train, y_test = train_test_split(tv, rating, test_size=0.33, random_state=42)

X Shape:  (10000, 1073289)
y Shape:  (10000,)


# (Optional) Oversample Data

In [18]:


"""tv = TfidfVectorizer(stop_words=None)
review = pd.Series(data['cleantext'])
rating = pd.Series(data['stars'])
#print(rating.type)
testing_tfidf = tv.fit_transform(review)
smt = SMOTE(random_state=42, k_neighbors = 1)
X_SMOTE, y_SMOTE = smt.fit_sample(testing_tfidf, rating)


X = X_SMOTE
y = y_SMOTE

#print('X Shape: ', X.shape)
#print('y Shape: ', y.shape)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
#print(y)
pd.DataFrame(X_SMOTE.todense()[y_SMOTE==2], columns= tv.get_feature_names())"""

tfidf = TfidfVectorizer(stop_words=None, max_features=100000, ngram_range=(1, 3))
lsvc = LinearSVC(multi_class='ovr')
lr = LogisticRegression(max_iter =1000)
SMOTE_pipeline = make_pipeline(tfidf,SMOTE(random_state=777),lr)
cv(10, data.cleantext, data.stars, SMOTE_pipeline, 'macro')


/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


0       U go n check car u wanna buy 1 Thats wrong mov...
1       Disgusting Groupon daughter tried outdated gau...
2       Ive eaten many time none bad last night Servic...
3       always fan Burlingtons deal however shopping o...
4       Another night meeting friend laugh Waited anot...
                              ...                        
9995    Yes rock hipster joint dig place little bit sc...
9996    4 star note folk rated place low must isolated...
9997    Im normally one jump reviewing chain restauran...
9998    Lets seewhat like Surprise Stadium Well 950 ta...
9999    45 location 45 star average think Arizona real...
Name: cleantext, Length: 10000, dtype: object
0       1
1       1
2       1
3       1
4       1
       ..
9995    5
9996    5
9997    5
9998    5
9999    5
Name: stars, Length: 10000, dtype: int64
              1            2             3            4            5
precision: [0.59493671 0.40206186 0.41791045 0.55084746 0.63988095]
recall:    [0.62666667 0.419

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


0       U go n check car u wanna buy 1 Thats wrong mov...
1       Disgusting Groupon daughter tried outdated gau...
2       Ive eaten many time none bad last night Servic...
3       always fan Burlingtons deal however shopping o...
4       Another night meeting friend laugh Waited anot...
                              ...                        
9995    Yes rock hipster joint dig place little bit sc...
9996    4 star note folk rated place low must isolated...
9997    Im normally one jump reviewing chain restauran...
9998    Lets seewhat like Surprise Stadium Well 950 ta...
9999    45 location 45 star average think Arizona real...
Name: cleantext, Length: 10000, dtype: object
0       1
1       1
2       1
3       1
4       1
       ..
9995    5
9996    5
9997    5
9998    5
9999    5
Name: stars, Length: 10000, dtype: int64
              1            2             3            4            5
precision: [0.55128205 0.42682927 0.45454545 0.55202312 0.59668508]
recall:    [0.57333333 0.376

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


0       U go n check car u wanna buy 1 Thats wrong mov...
1       Disgusting Groupon daughter tried outdated gau...
2       Ive eaten many time none bad last night Servic...
3       always fan Burlingtons deal however shopping o...
4       Another night meeting friend laugh Waited anot...
                              ...                        
9995    Yes rock hipster joint dig place little bit sc...
9996    4 star note folk rated place low must isolated...
9997    Im normally one jump reviewing chain restauran...
9998    Lets seewhat like Surprise Stadium Well 950 ta...
9999    45 location 45 star average think Arizona real...
Name: cleantext, Length: 10000, dtype: object
0       1
1       1
2       1
3       1
4       1
       ..
9995    5
9996    5
9997    5
9998    5
9999    5
Name: stars, Length: 10000, dtype: int64
              1            2             3            4            5
precision: [0.51948052 0.44565217 0.41044776 0.54471545 0.61280488]
recall:    [0.53333333 0.440

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


0       U go n check car u wanna buy 1 Thats wrong mov...
1       Disgusting Groupon daughter tried outdated gau...
2       Ive eaten many time none bad last night Servic...
3       always fan Burlingtons deal however shopping o...
4       Another night meeting friend laugh Waited anot...
                              ...                        
9995    Yes rock hipster joint dig place little bit sc...
9996    4 star note folk rated place low must isolated...
9997    Im normally one jump reviewing chain restauran...
9998    Lets seewhat like Surprise Stadium Well 950 ta...
9999    45 location 45 star average think Arizona real...
Name: cleantext, Length: 10000, dtype: object
0       1
1       1
2       1
3       1
4       1
       ..
9995    5
9996    5
9997    5
9998    5
9999    5
Name: stars, Length: 10000, dtype: int64
              1            2             3            4            5
precision: [0.47727273 0.35051546 0.39285714 0.52762431 0.63897764]
recall:    [0.56       0.365

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


0       U go n check car u wanna buy 1 Thats wrong mov...
1       Disgusting Groupon daughter tried outdated gau...
2       Ive eaten many time none bad last night Servic...
3       always fan Burlingtons deal however shopping o...
4       Another night meeting friend laugh Waited anot...
                              ...                        
9995    Yes rock hipster joint dig place little bit sc...
9996    4 star note folk rated place low must isolated...
9997    Im normally one jump reviewing chain restauran...
9998    Lets seewhat like Surprise Stadium Well 950 ta...
9999    45 location 45 star average think Arizona real...
Name: cleantext, Length: 10000, dtype: object
0       1
1       1
2       1
3       1
4       1
       ..
9995    5
9996    5
9997    5
9998    5
9999    5
Name: stars, Length: 10000, dtype: int64
              1            2             3            4            5
precision: [0.48837209 0.35106383 0.43650794 0.54624277 0.65229885]
recall:    [0.56       0.354

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


0       U go n check car u wanna buy 1 Thats wrong mov...
1       Disgusting Groupon daughter tried outdated gau...
2       Ive eaten many time none bad last night Servic...
3       always fan Burlingtons deal however shopping o...
4       Another night meeting friend laugh Waited anot...
                              ...                        
9995    Yes rock hipster joint dig place little bit sc...
9996    4 star note folk rated place low must isolated...
9997    Im normally one jump reviewing chain restauran...
9998    Lets seewhat like Surprise Stadium Well 950 ta...
9999    45 location 45 star average think Arizona real...
Name: cleantext, Length: 10000, dtype: object
0       1
1       1
2       1
3       1
4       1
       ..
9995    5
9996    5
9997    5
9998    5
9999    5
Name: stars, Length: 10000, dtype: int64
              1            2             3            4            5
precision: [0.49438202 0.41463415 0.41428571 0.52513966 0.63444109]
recall:    [0.58666667 0.365

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


0       U go n check car u wanna buy 1 Thats wrong mov...
1       Disgusting Groupon daughter tried outdated gau...
2       Ive eaten many time none bad last night Servic...
3       always fan Burlingtons deal however shopping o...
4       Another night meeting friend laugh Waited anot...
                              ...                        
9995    Yes rock hipster joint dig place little bit sc...
9996    4 star note folk rated place low must isolated...
9997    Im normally one jump reviewing chain restauran...
9998    Lets seewhat like Surprise Stadium Well 950 ta...
9999    45 location 45 star average think Arizona real...
Name: cleantext, Length: 10000, dtype: object
0       1
1       1
2       1
3       1
4       1
       ..
9995    5
9996    5
9997    5
9998    5
9999    5
Name: stars, Length: 10000, dtype: int64
              1            2             3            4            5
precision: [0.48863636 0.37373737 0.40650407 0.52147239 0.59065934]
recall:    [0.57333333 0.402

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


0       U go n check car u wanna buy 1 Thats wrong mov...
1       Disgusting Groupon daughter tried outdated gau...
2       Ive eaten many time none bad last night Servic...
3       always fan Burlingtons deal however shopping o...
4       Another night meeting friend laugh Waited anot...
                              ...                        
9995    Yes rock hipster joint dig place little bit sc...
9996    4 star note folk rated place low must isolated...
9997    Im normally one jump reviewing chain restauran...
9998    Lets seewhat like Surprise Stadium Well 950 ta...
9999    45 location 45 star average think Arizona real...
Name: cleantext, Length: 10000, dtype: object
0       1
1       1
2       1
3       1
4       1
       ..
9995    5
9996    5
9997    5
9998    5
9999    5
Name: stars, Length: 10000, dtype: int64
              1            2             3            4            5
precision: [0.5        0.41791045 0.39333333 0.56695157 0.6497006 ]
recall:    [0.65333333 0.304

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


0       U go n check car u wanna buy 1 Thats wrong mov...
1       Disgusting Groupon daughter tried outdated gau...
2       Ive eaten many time none bad last night Servic...
3       always fan Burlingtons deal however shopping o...
4       Another night meeting friend laugh Waited anot...
                              ...                        
9995    Yes rock hipster joint dig place little bit sc...
9996    4 star note folk rated place low must isolated...
9997    Im normally one jump reviewing chain restauran...
9998    Lets seewhat like Surprise Stadium Well 950 ta...
9999    45 location 45 star average think Arizona real...
Name: cleantext, Length: 10000, dtype: object
0       1
1       1
2       1
3       1
4       1
       ..
9995    5
9996    5
9997    5
9998    5
9999    5
Name: stars, Length: 10000, dtype: int64
              1            2             3            4            5
precision: [0.57142857 0.44761905 0.44067797 0.56214689 0.64450867]
recall:    [0.58666667 0.510

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


0       U go n check car u wanna buy 1 Thats wrong mov...
1       Disgusting Groupon daughter tried outdated gau...
2       Ive eaten many time none bad last night Servic...
3       always fan Burlingtons deal however shopping o...
4       Another night meeting friend laugh Waited anot...
                              ...                        
9995    Yes rock hipster joint dig place little bit sc...
9996    4 star note folk rated place low must isolated...
9997    Im normally one jump reviewing chain restauran...
9998    Lets seewhat like Surprise Stadium Well 950 ta...
9999    45 location 45 star average think Arizona real...
Name: cleantext, Length: 10000, dtype: object
0       1
1       1
2       1
3       1
4       1
       ..
9995    5
9996    5
9997    5
9998    5
9999    5
Name: stars, Length: 10000, dtype: int64
              1            2             3            4            5
precision: [0.51136364 0.41573034 0.41984733 0.57848837 0.64655172]
recall:    [0.60810811 0.397

#5a) Use Linear SVC Model

In [9]:
#Linear SVC
svc = LinearSVC(multi_class='ovr')
svc.fit(X_train, y_train)

LSVCpredictions = svc.predict(X_test)

print(confusion_matrix(y_test, LSVCpredictions))
print('\n')
print(classification_report(y_test,LSVCpredictions))

[[ 87  20  17  72  78]
 [ 24  29  39 148  73]
 [  4  11  47 330  86]
 [  0   1  16 734 399]
 [  2   0   2 343 738]]


              precision    recall  f1-score   support

           1       0.74      0.32      0.45       274
           2       0.48      0.09      0.16       313
           3       0.39      0.10      0.16       478
           4       0.45      0.64      0.53      1150
           5       0.54      0.68      0.60      1085

    accuracy                           0.50      3300
   macro avg       0.52      0.37      0.38      3300
weighted avg       0.50      0.50      0.46      3300



#5b) Use Multinomial Naive Bayes Model

In [ ]:
#Multinomial Naive Bayes
nb = MultinomialNB()
nb.fit(X_train, y_train)

NBpredictions = nb.predict(X_test)

print(confusion_matrix(y_test, NBpredictions))
print('\n')
print(classification_report(y_test,NBpredictions))

[[1053   92    1    9    1]
 [  51 1066    0   17    4]
 [  92  487  167  384   22]
 [  45  200    9  775  125]
 [  83  123    3  549  460]]


              precision    recall  f1-score   support

           1       0.80      0.91      0.85      1156
           2       0.54      0.94      0.69      1138
           3       0.93      0.14      0.25      1152
           4       0.45      0.67      0.54      1154
           5       0.75      0.38      0.50      1218

    accuracy                           0.61      5818
   macro avg       0.69      0.61      0.57      5818
weighted avg       0.69      0.61      0.56      5818



# 5c) Use SVC Model

In [ ]:
#SVC
clf = svm.SVC()
clf.fit(X_train, y_train)

CLFpredictions = clf.predict(X_test)

print(confusion_matrix(y_test, CLFpredictions))
print('\n')
print(classification_report(y_test,CLFpredictions))

[[1085    7    2   51   11]
 [  12 1007    4   97   18]
 [  11   22  749  323   47]
 [   2    2    7  837  306]
 [   2    1    2  435  778]]


              precision    recall  f1-score   support

           1       0.98      0.94      0.96      1156
           2       0.97      0.88      0.93      1138
           3       0.98      0.65      0.78      1152
           4       0.48      0.73      0.58      1154
           5       0.67      0.64      0.65      1218

    accuracy                           0.77      5818
   macro avg       0.82      0.77      0.78      5818
weighted avg       0.81      0.77      0.78      5818



# 5d) Use RFC Model

In [ ]:
#RFC
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)

RFCpredictions = rfc.predict(X_test)

print(confusion_matrix(y_test, RFCpredictions))
print('\n')
print(classification_report(y_test,RFCpredictions))

[[1082    2   35   22   15]
 [   5 1012   54   43   24]
 [  15    8  975  100   54]
 [   9   37  162  534  412]
 [  12   19   98  311  778]]


              precision    recall  f1-score   support

           1       0.96      0.94      0.95      1156
           2       0.94      0.89      0.91      1138
           3       0.74      0.85      0.79      1152
           4       0.53      0.46      0.49      1154
           5       0.61      0.64      0.62      1218

    accuracy                           0.75      5818
   macro avg       0.75      0.75      0.75      5818
weighted avg       0.75      0.75      0.75      5818



# 5e) Use KNN Model

In [ ]:
#KNN
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
KNNpredictions = knn.predict(X_test)

print(confusion_matrix(y_test, KNNpredictions))
print('\n')
print(classification_report(y_test,KNNpredictions))

[[ 894    0  262    0    0]
 [   0  824  314    0    0]
 [   2    0 1150    0    0]
 [   2    3 1144    0    5]
 [   5    5 1196    1   11]]


              precision    recall  f1-score   support

           1       0.99      0.77      0.87      1156
           2       0.99      0.72      0.84      1138
           3       0.28      1.00      0.44      1152
           4       0.00      0.00      0.00      1154
           5       0.69      0.01      0.02      1218

    accuracy                           0.49      5818
   macro avg       0.59      0.50      0.43      5818
weighted avg       0.59      0.49      0.43      5818



# 5f) Use Logistic Regression

In [ ]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
LRpredictions = lr.predict(X_test)

print(confusion_matrix(y_test, LRpredictions))
print('\n')
print(classification_report(y_test,LRpredictions))

[[1071   40   32    4    9]
 [  46  990   68   24   10]
 [  35   86  855  133   43]
 [  23   57  185  580  309]
 [  29   24  133  296  736]]


              precision    recall  f1-score   support

           1       0.89      0.93      0.91      1156
           2       0.83      0.87      0.85      1138
           3       0.67      0.74      0.71      1152
           4       0.56      0.50      0.53      1154
           5       0.66      0.60      0.63      1218

    accuracy                           0.73      5818
   macro avg       0.72      0.73      0.72      5818
weighted avg       0.72      0.73      0.72      5818



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
